#!/bin/bash -e

ver=2
cov_file="v${ver}-0000-cover-letter.patch"

git format-patch \
    --cover-letter \
    --thread \
    -v "$ver" \
    --to git@vger.kernel.org
    --cc 'Junio C Hamano <gitster@pobox.com>' \
    --cc 'Johannes Schindelin <johannes.schindelin@gmx.de>' \
    --cc 'Christian Couder <chriscool@tuxfamily.org>' \
    --cc kernel-team@fb.com \
    "$(git rev-parse origin/master)"..

sed -i 's/\*\*\* SUBJECT HERE \*\*\*/bisect: status improvements when bisect is not fully fleshed out/' "$cov_file"

cat << 'EOF' >> "$cov_file"
When bisecting, we currently don't output anything before bisection starts in
earnest, which can result in some confusion. For example, in the case
illustrated in the first commit in this patch series, it's trivial to
accidentally misspell a tag or branch and accidentally end up in an unintended
state with no clear indication about what happened.

This patch series makes it so that we give information about bisect state even
before the bisect is ready to begin, and also stores those changes in state to
the bisect log.
EOF
