#!/bin/bash -e

# Given a bunch of kmsg entries that look like this:
#
# [   92.983404][  T275] CPU: 0 PID: 275 Comm: leaker Tainted: G    B D           5.4.0-rc6-mm1-00345-g5d58bdfa52b9 #265
# [   92.983407][  T112] Code: 82 e8 d7 97 51 00 e9 2f fe ff ff 90 90 55 48 89 e5 41 57 41 56 41 55 41 54 49 89 fc 53 48 83 ec 18 48 89 75 c8 e8 63 2f 06 00 <49> 83 3c 24 ff 0f 84 9d 09 00 00 4c 89 e7 4d 8d 6c 24 08 4c 89 e3
# [   92.983410][   T80] RSP: 0018:ffff88806a07f3d8 EFLAGS: 00010086
#
# separate them into a file per-thread, and remove text addresses found on the
# stack that weren't found by the unwinder

while IFS='' read -r line; do
    IFS=' []' read -r _ time _ thread dubious _ <<< "$line"

    # Throw away if not found by unwinder
    [[ $dubious == "?" ]] && continue

    printf '%s\n' "$line" >> "kmsg_$thread"
done
